apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
  - namespace.yaml
  - admin-password.yaml
  - database.yaml
  - release.yaml

configMapGenerator:
  - name: vaultwarden-values
    namespace: vaultwarden
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
