configMapGenerator:
  - name: longhorn-values
    namespace: longhorn-system
    files:
      - values.yaml
namespace: longhorn-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
