apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mumble

resources:
  - namespace.yaml
  - repository.yaml
  - certificate.yaml
  - release.yaml

configMapGenerator:
  - name: mumble-values
    namespace: mumble
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
