persistence:
  enabled: true
  size: 5Gi
  storageClass: nfs-client

config:
  welcometext: "Welcome to our Mumble server!"
  registerName: "Gaming with the Borg"
  bandwidth: "130000"
  users: "10"
  certrequired: "true" # Require client certificates
  sslCert: "/var/run/secrets/mumble-tls/tls.crt"
  sslKey: "/var/run/secrets/mumble-tls/tls.key"
  sqliteWal: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
    cpu: "1"

service:
  type: LoadBalancer
