apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-catalogs
  namespace: cnpg-system
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: cloudnative-pg-artifacts
  prune: true
  path: ./image-catalogs

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudnative-pg-artifacts
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://github.com/cloudnative-pg/artifacts.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include image-catalogs dir
    !/image-catalogs
