apiVersion: v1
stringData:
  api-token: ENC[AES256_GCM,data:QIUIDgeL4a30ZTixVx0BPlTs7TAmrcMdBPpfqBC08mpKT9NWgA2YmxeQY7AH9ntcqZNu2l6+4BflSrZU,iv:+AVKF/jPdyr8+r+Vs9qWVTYNYFAvkUbxgyUq6c5LeAA=,tag:mBAJ+GQ06dL4KdmxuYOCxA==,type:str]
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDNOTEl0eUtYQVRUUjU2
        cXhZUlVpcEt3YnlXRHVBNm5nT3hXWDdybUg4ClVzZkZ6WUtCYU1LV1ZITm1idEtk
        c3NObjA3WExITDFpc2xCdUNyVXZ0OVEKLS0tIEFPQ3hhM21Zbzd6VUtUS2EzaDg3
        dnpsQUdFVnZKMFd1VU8rTWJOUGFvSzgKzH6K5kgInKZ/vzXWkipidl4bkjrH60eA
        nA2lEiNBP9JhgGpqu5F9T88Tw4qGh3uOC8YGLwAD4uCdvKj2g5hvFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T16:00:27Z"
  mac: ENC[AES256_GCM,data:MNtgE+R6OH+hnP/AHcMht2L1jWBLNnR7LYg8m1DWnSXOu3N/6FfoE/mBrnnGAYjD5JBc1/AqQYD+cBBMAE8jPinZPfMQna5zh92Wvtr0vRY4kRDc0LVoSmA0lrUCiFNIgGyVgBao5E7PaoKDW5d+ZSPO7aEKjBxD+sPOfAFfdlw=,iv:agVzsg7qmdYDSVcds6L8jnSarAV2HarVpqDgXGu4Al0=,tag:Wq956nNmGSfXEjvkmTzGvA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
