apiVersion: v1
stringData:
  api-token: ENC[AES256_GCM,data:8N0W0r6AVTPie24DZzcn0c0Vh6cpdQhuCbAoyUhAop6RPCnSkC0rkQ==,iv:nIRYl2Il+SY1myDZv4jzpHyLKunKU7fqY/Aa/lxp73A=,tag:Yiha5EIRYnOF75uIMyM2bg==,type:str]
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDNOTEl0eUtYQVRUUjU2
        cXhZUlVpcEt3YnlXRHVBNm5nT3hXWDdybUg4ClVzZkZ6WUtCYU1LV1ZITm1idEtk
        c3NObjA3WExITDFpc2xCdUNyVXZ0OVEKLS0tIEFPQ3hhM21Zbzd6VUtUS2EzaDg3
        dnpsQUdFVnZKMFd1VU8rTWJOUGFvSzgKzH6K5kgInKZ/vzXWkipidl4bkjrH60eA
        nA2lEiNBP9JhgGpqu5F9T88Tw4qGh3uOC8YGLwAD4uCdvKj2g5hvFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T16:17:16Z"
  mac: ENC[AES256_GCM,data:bgAcKx+3c7pu9h2vSZUVxn6yN+HpYl3i3x6vOBhg6+z5m2KBssJaO2Y3ys3e6jREYo4mvNfpVmxqaYjvHvjy8khd3X1aOyMtE+ZfxXkX8hawqjub//nYpnJ8ESSYgu52AWOnqXtrjs8fZzvqm3p64kVNecxnFDWAvYsEkmLkj2M=,iv:efOwlpjjwZeHZmwvlW+pTqMmgv7HzLDBGLUO+Fne/rU=,tag:OEmlAsDCO/PcZp6OmStV7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
