apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - cloudflare-data.yaml
  - cluster-issuers.yaml
  - cloudnative-pg-catalogs.yaml
  - notifications-ingress.yaml
configurations:
  - kustomizeconfig.yaml
