apiVersion: v1
kind: Secret
metadata:
  name: copyparty-config
type: Opaque
stringData:
  config.conf: ENC[AES256_GCM,data:ozY36HwXmcqhOQUr9HVAZAV4kEA/MdkaY8kue6qC4YfKao2IcU8I7MmzJE/DOpJzQ2esQHVWdm8tVuQRfOhmigm4mSMggO1xJFB6sjzDboriW7DzKsMjxRrYhDUUqKrXljo3PzC+GGs3mkkQ1Wa9CQsP0yd0FLSCDwutCI2Oapcd206bk9UqK2/5PmfPDFIVqDAjHxoNphzm3GENQHLO9cBvpl5tmxVgGs0Tl/SoWjhk8FKuhupgAxqAL+u7Z7wux9CPaM7pkwfOUSQGjri7IHup4mFwSIAu9Oant4tYbESNPMhW2mmlcPpw0MtzBbBZ1KGgzL15NfU/B1MKM9ehAx8QrPgAIFaUCvn9ww76uur2kIFMakPZsxEaFAm3GZKSqjcDHq1X9txVdGw4zIIaBoR66Y4=,iv:ziOHWsHTN3Fc/Tj6bBBMXrftkz3o+Y7IZ4FmXkin7+s=,tag:K0mL22eCysQWBOIDNgh4Kg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRmhRcVhpN0piWE5rS3dC
        TDJxVjJMSGhDVi91TkFVTkw5UHdRenNFdXlRCjNOYVpiQW5WYmgyaXBYa2V6V1RM
        WGlUb2crMjYxby9JbEo3dmNrWVBTWmcKLS0tIFRmRVhWT1d4OXhtTzE0elV0RHQw
        eHdMcGhRb0VQZnJRakFMdkdBOE9iTmsK3+1ntO6T7f5ypuI1L2UkHREZtBN2yiz2
        2LM69CRO26of59QLgSJ+Nu+tQU3QgbBFQjwR/V7017ap3M+lq2pcIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T19:32:49Z"
  mac: ENC[AES256_GCM,data:Nz4Kh40zzPY5S5YQXcLaaTNDQeBz7Wk4ifh+FVy7fP0IGriKIhQ+ad8FkP2pCRrncZWt+/gHKWZZKHuZZvSsErHj2WGrDfwm2famkRrM640R1kNGvw2GcEH7piyWxeU48v7n6sUi4HdzpJStkWsOibC21fkpMqUFUF/XMxmOOw4=,iv:hq/DkXK5qvSJLCfMbruLho2ioOXIcODgd5eHu5JWVFY=,tag:qPt7HCiw+bmXZvMqEV6ciQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: copyparty-metrics-admin-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:WdBa62j+AhT2OlWXuA==,iv:itEr7rh0fUbzMPkTHXh39Ejr7JlKjlxJcLTOmf1ohRQ=,tag:XM1IT7VLCpH3C8cdMZ2v2A==,type:str]
  password: ENC[AES256_GCM,data:PYPM1JMwJKLtixGa5AadgnvH,iv:IK3C3bCwvSJ6ECsP7in9o0VbauMRyD5El48uJ8OUWQ0=,tag:Gmp4+pN8Zc8mJVUzP5rUBg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hu3ypqyxgvdsjkt2cts6lrn8p0n0gvr4j0xxm5sq22d8ktscg5ysn23mzv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRmhRcVhpN0piWE5rS3dC
        TDJxVjJMSGhDVi91TkFVTkw5UHdRenNFdXlRCjNOYVpiQW5WYmgyaXBYa2V6V1RM
        WGlUb2crMjYxby9JbEo3dmNrWVBTWmcKLS0tIFRmRVhWT1d4OXhtTzE0elV0RHQw
        eHdMcGhRb0VQZnJRakFMdkdBOE9iTmsK3+1ntO6T7f5ypuI1L2UkHREZtBN2yiz2
        2LM69CRO26of59QLgSJ+Nu+tQU3QgbBFQjwR/V7017ap3M+lq2pcIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-06T19:32:49Z"
  mac: ENC[AES256_GCM,data:Nz4Kh40zzPY5S5YQXcLaaTNDQeBz7Wk4ifh+FVy7fP0IGriKIhQ+ad8FkP2pCRrncZWt+/gHKWZZKHuZZvSsErHj2WGrDfwm2famkRrM640R1kNGvw2GcEH7piyWxeU48v7n6sUi4HdzpJStkWsOibC21fkpMqUFUF/XMxmOOw4=,iv:hq/DkXK5qvSJLCfMbruLho2ioOXIcODgd5eHu5JWVFY=,tag:qPt7HCiw+bmXZvMqEV6ciQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
