apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: copyparty
resources:
  - namespace.yaml
  - repository.yaml
  - config.yaml
  - release.yaml

configMapGenerator:
  - name: copyparty-values
    files:
      - values.yaml
