apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - repository.yaml
  - pvc.yaml
  - release.yaml
  - oauth-secret.yaml
  - database.yaml
  - database-secret.yaml

configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
