apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oidc-roles
  - ./binfmt.yaml
  - nfs-provisioner
  - prometheus
  - ./cert-manager.yaml
  - ./secret-reflector.yaml
  - ./tailscale
  - ./metallb
configurations:
  - kustomizeconfig.yaml
