apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./binfmt.yaml
  - prometheus
  - ./cert-manager.yaml
  - ./secret-reflector.yaml
  - ./tailscale
  - ./metallb
  - ./velero
configurations:
  - kustomizeconfig.yaml
